# Generated by Django 4.2.16 on 2024-09-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tran_id', models.CharField(max_length=255, unique=True)),
                ('response_data', models.JSONField()),
                ('status', models.IntegerField(choices=[(0, 'Unpaid'), (1, 'Paid')], default=0)),
            ],
        ),
    ]
